pool: 15 #may be ommited, default=60
masters:
  - name: "master1" #this should be a SUCCESS write
    address: "master1"
    port: 6379
    pass: "123456"
    slaves:
      - name: "slave1" #this should be SUCCESS read
        address: "slave1"
        port: 6379
        pass: "123456"
      - name: "slave2" #this should be FAILURE read because it isn't configured as slave of master1
        address: "slave2"
        port: 6379
        pass: "123456"
      - name: "slave3" #this should be a FAILURE read because a pass is not needed
        address: "slave3"
        port: 6379
        pass: "123456"
  - name: "master2a" #this should be a SUCCESS write even without a password
    address: "master2"
    port: 6379
    pass: ""
    slaves:
      - name: "slave3" #this should be a SUCCESS read even without a password
        address: "slave3"
        port: 6379
        pass: ""
      - name: "slave99" #this should be a FAILURE to resolve
        address: "slave99"
        port: 6379
        pass: ""
  - name: "master2b" #this should be a SUCCESS write with minimal config
    address: "master2"
    slaves:
      - address: "slave3" #this should be a SUCCESS read with minimal config, while being listed as Unnamed
  - name: "slave3b"
    address: "slave3" #this should be a FAILURE to write since it's a slave
    slaves:
      - address: "slave4" #this shouldn't even be tested
  - name: "master2c" #this should be a FAILURE because of connection refused
    address: "master2"
    port: 6380
    slaves:
      - address: "slave4" #this shouldn't even be tested
